export const DECREMENT = 'DECREMENT'
export const INCREMENT = 'INCREMENT'
export const CLEAR = 'CLEAR'
export const PLUSTEN = 'PLUSTEN'
export const PLUSNUMBER = 'PLUSNUMBER'
export const FETCH_PIC = 'FETCH_PIC'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'